services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  redis-server:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  ms-parquimetro-control:
    build: .
    ports:
      - "8091:8091"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_HOST=mongodb:27017
      - JAVA_TOOLS_OPTIONS=-Dfile.encoding=UTF-8

networks:
  default:
    name: parquimetro-network

volumes:
  mongodb: