services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: parquimetro_cadastro_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  ms-parquimetro-cadastro:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - postgresql
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_DB: parquimetro_cadastro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

networks:
  default:
    external: true
    name: parquimetro-cadastro-network